#!bin/bash
dnf list installed mysql -y
if [ $? -ne 0 ]
then
    echo "Mysql not installed, going to installaing"
    dnf install mysql -y
    if [ #? -ne 0 ]
    then
        echo "Mysql installation failure"
        exit 1
    else
        echo "Mysql installation success"
    fi
else
    echo "Mysql is already installed"
fi            